### ISSUE TITLE
[Option Request] Ability to disable variant tokens

### ISSUE THREAD

**Issue by roguedevjake** [vtt-lair/token-replacer#101]
An option to force closest match and not randomize a variant token for subsequent drags past the first would be nice. 

CR/Type matching doesn't really help when dealing with colour variants having minorly different stat blocks sadly.

**Comment by vtt-lair** [comment]
@roguedevjake if I understand you correctly, this should already be possible.

Once you've dragged the token onto the canvas and it has changed. Open the actor, open the prototype token, go to the Appearance tab and there will be a Token Replacer option that disables the replacement. If you tick that, any future token placements will use the already selected image.
