### ISSUE TITLE
When on active scene, Players(Not GM) gets errors when the GM copy and pastes tokens

### ISSUE THREAD

**Issue by MagicOriole** [vtt-lair/token-replacer#103]
Used Find Culprit to confirm its Token Replacer.
Also did manual testing of disabling everything but Token Replacer (and tokenizer dependant)

(LEFT IS GM - RIGHT IS PLAYER)
![chrome_4XrV9kpLt7](https://user-images.githubusercontent.com/96490347/199033295-308cff72-f9fe-4065-8f60-83e768e2426f.gif)

Copying and Pasting tokens with TOKEN REPLACER disabled does not give player Errors.

**Comment by MagicOriole** [comment]
Also verified USER PERMISSIONS were granting permissions to players regarding Tokens and Actors.

**Comment by vtt-lair** [comment]
I'm releasing a new version in the next few minutes that should fix this. Please let me know.
