### ISSUE TITLE
Allow configurable token folder

### ISSUE THREAD

**Issue by Blesmol** [vtt-lair/token-replacer#22]
Currently the token folder is generated by the module below the module install folder. This causes problems like #21, and also is "unfortunate" in hosted environments like in forge-vtt.com, where there is a better separation between module data and user assets.

Thus I would propose to add a configurable option that allows users to define the token path. Default could be to the current directory to not break things for existing users.

**Comment by vtt-lair** [comment]
@Blesmol, that is the next change I'm going to implement. Planning on working on this, this weekend.

**Comment by Blesmol** [comment]
Great, thanks, looking forward to it!

**Comment by vtt-lair** [comment]
@Blesmol new release has been created and release on Foundry. Have added the requested configurable token folder, that defaults to the folder in the module. Please remember to move your own tokens out of that folder before updating and then change the folder in the settings.

**Comment by Blesmol** [comment]
Great, thanks!
