### ISSUE TITLE
Cannot save empty "NPC Difficulty name"

### ISSUE THREAD

**Issue by Eregar43** [vtt-lair/token-replacer#26]
When I try to save the options after I removed the "cr" from the Field for "NPC Difficulty name", I get this error and it does not save.

TypeError: Assignment to constant variable.
    at TokenReplacerSetup._updateObject (token-replacer.js:68)
    at TokenReplacerSetup._onSubmit (foundry.js:5251)

In row 68 the code tries to change "diffVariable", but that is a constant.

**Comment by vtt-lair** [comment]
This has been fixed and released as a hotfix in v0.2.1
