### ISSUE TITLE
Unhandled exceptions

### ISSUE THREAD

**Issue by MSAbaddon** [vtt-lair/token-replacer#41]
Currently, there are a few unhandled exceptions your module generates:

![image](https://user-images.githubusercontent.com/66370966/106503915-89046180-64c6-11eb-8baa-4d3ec25ce098.png)

![image](https://user-images.githubusercontent.com/66370966/106504058-bc46f080-64c6-11eb-9c18-b097436fe29e.png)

Happens every time I reload Foundry using F5

**Comment by NiceTSY** [comment]
I do have the same problem, with and without any other module.
This prevents Token Replacer to work correctly :(

**Comment by vtt-lair** [comment]
Thanks guys for the report. I'll look at it this weekend. Life just got in the way the last week.

**Comment by vtt-lair** [comment]
I've added some defensive checks around the errors, and also some debug logs functionality. This will be released in a few minutes
