### ISSUE TITLE
Creature matching fails if there's a space in a folder in the path

### ISSUE THREAD

**Issue by GuiSim** [vtt-lair/token-replacer#51]
`cachedTokens` will contain `%20` but `tokenCheck` will contain a space character ` `.

My suggestion on this would be to ignore folder names. Cache only file names and remove the CR check.
After that, match purely in Actor name VS File name.

The only situation I'd see this becoming an issue would be if there's two monsters with the same name in two different CRs. I know that for 5e this isn't possible as every monster has a unique name.

EDIT: The default Forgotten-Adventures token folder name for Patreon is `Tokens (Patreon)`. Renaming to `Tokens_Patreon` resolved my issue.

EDIT2: Due to the `indexOf` check, this could be an issue if there's a CR 1 creature named "Goblin" and a CR 2 creature named "Goblin Archer". By adding a "Goblin" token, both creatures would be matched as they both contain the string "Goblin".

This is subjective, but my opinion is that CR shouldn't be the differenciating factor as you could have the same problem if both had the same CR. A more strict check than `indexOf` would allow clearer matching. Perhaps allow users to configure their name convention for tokens?
e.g. `${data.name}_${data.data.traits.size}_${data.data.details.type}`
This might be too flexible and complex though.

**Comment by vtt-lair** [comment]
I'll have a look at this. Alternately what you can currently do is remove the cr value from the NPC Difficulty Name and put everything in the root folder, that way the programs looks at all the files without worrying about folder structure.

I'll add some escapes around the whole string as well (currently just escaping the file names). That should at least fix any issue with spaces and other funky characters that get's replaced with HTML encoded values in the folder names too.

**Comment by vtt-lair** [comment]
I've added some new basic functionality to define how the folder and image file names are defined. This way you can specify whether your folder and file names use spaces, underscores or dashes between the words.

So if you select the "Proper English" version for both folders and files, it'll be expecting "/cr 1/Monster Name.png".
If you select "Underscored" for both, it'll expect "cr_1/Monster_Name.png".
If you select "No Space" and "Underscored" for the folder and file names respectively (this is seen as default), it'll expect "/cr1/Monster_Name.png".

If you don't specify a NPC Difficulty name, it will ignore the folder and just compare things in the root folder.

_This will be released later this week_
