### ISSUE TITLE
One more error message

### ISSUE THREAD

**Issue by MSAbaddon** [vtt-lair/token-replacer#52]
Hi there,
did several tests and the module seems to work for me most of the time. It's a bit troublesome that it only tries once to update an actor the moment the token is dragged to the scene and that it means reloading the page if something goes wrong - but that is a managable drawback.

I still get an error message the moment I create a new npc actor in the actor tab, but the module still seems to work fine.
![image](https://user-images.githubusercontent.com/66370966/107194466-5b507880-69f0-11eb-87df-0204b4270a07.png)

**Comment by vtt-lair** [comment]
Thanks @MSAbaddon I'll have a look.

**Comment by vtt-lair** [comment]
Fix for this will be released some time this week.

**Comment by MSAbaddon** [comment]
Nice :-)
