### ISSUE TITLE
[Feature Suggestion] Allow Toggling Token Replacer Off for Individual Actors

### ISSUE THREAD

**Issue by friction1** [vtt-lair/token-replacer#57]
While some may find the shuffle feature useful, I find that it causes more trouble than help. I would love if when I bring in an actor that it finds the best match for the token and then stays static. Another solution is just to be able to turn off token replacer on individual actors so you can pick one image and avoid having it replace the chosen images. 

Thank you for your hard work on this module. It's a real time saver.

**Comment by vtt-lair** [comment]
@friction1 thank you for the suggestion. I'm currently testing an implementation of you suggestion and still want to double check how it interacts with newly created actors, compendium actors and also interactions when manually changing the token.

The current solution will have a "disable" on the Image tab of the Prototype Toke/Token form. If that disable is toggled, it won't replace the art work. Theoretically this should work with manually set tokens as well as tokens that were set on creation by Token Replacer, but then disabling it for that actor won't change the images going forward.

Hope to have it out later this week.
