### ISSUE TITLE
Replacement not working for actors with multi-word names

### ISSUE THREAD

**Issue by The-Grison** [vtt-lair/token-replacer#59]
Thanks for making this! I love the functionality and I have it partially working, but I'm having a few issues:

1) My token and portrait replacements function correctly, but only **for actors with single-word names** (e.g., "Goblin"). For actors with multi-word names (e.g, "Bandit Captain"), no replacements occur and the existing artwork is retained.
2) I added portrait images to the same image directory, prefacing filenames with "Av_" (avatar) and specifying "Av_" as the portrait preface string. Portraits replacements work (at least for single-word-named actors), but this introduced a new issue: The wildcard token matching also selects the portrait images ("Av_Actor_Name") as matches, so I get a mix of token and portrait art each time I drag an actor token onto a scene.

**EDIT: I was able to resolve both of these issues by selecting the "Use NPC Difficulty Folder Structure" setting, even though _I'm not actually using such a folder_.**
- With this option selected, multi-word actor names now match filenames as expected.
- With this option selected, wildcard matching only applies *after* the Actor name, thus respecting the profile prefix. 
- Without this option selected, wildcard matching seems to apply *before and after* the actor name -- thus ignoring the profile prefix and matching those files as well.

**Finally, I have a feature suggestion:**
- In order to reduce the need to group tokens by CR, it would be great to have a "strict wildcards" setting available. This setting would still allow wildcard matches, but would restrict them to a specified format to eliminate undesired matches. For example, strict wildcards might only match files of the format Actor Name_## (e.g., "Goblin_01", "Goblin_02", etc.) but would ignore "Goblin Captain." This would eliminate the need to group assets by CR to avoid false matches, while still enabling wildcard matches where desired.
- Alternatively, a setting to "disable wildcard matching" would also address the CR folder issue, but would be less flexible overall.

Thanks again!
- Jeff

**Comment by vtt-lair** [comment]
Thanks, will have a look at this during the week.

**Comment by vtt-lair** [comment]
@The-Grison I'm glad to see that you were able to resolve the issue. Can you possibly share a screenshot of your token folder for me please? The "Use NPC Difficulty Folder Structure" is supposed to then use the NPC Variable setting (cr by default) to look for the images in a structure where the files are saved into those difficulty folders. Just want to see if I can replicate the issue that you were experiencing

For instance mine is setup as:
![image](https://user-images.githubusercontent.com/33215552/112798128-c0c5fa80-906c-11eb-9e30-73277412b60e.png)

And then the files are setup as:
![image](https://user-images.githubusercontent.com/33215552/112798152-ca4f6280-906c-11eb-9c31-671239fee695.png)

And my settings are then:
![image](https://user-images.githubusercontent.com/33215552/112798226-e81cc780-906c-11eb-91c3-cf42aa0a14de.png)
![image](https://user-images.githubusercontent.com/33215552/112798202-e05d2300-906c-11eb-9c72-51072b152eda.png)

Which basically _should_ translate to:
Look for the images in the directory. The images will be in a folder structure defined by the NPC Difficult Name, using No Spaces in the folder name (eg. cr1, cr2 etc). The images will use Underscores between the names (eg Animated_Armor_1.png, Animated_Armor_2.png etc)

If I removed the "Use NPC Difficulty Folder Structure", it would just look for the images in the Directory and not worry about the subfolders.

**Comment by The-Grison** [comment]
I’m happy to send a screenshot, but just to be clear, my token folder is just a single folder with no subfolders. I only checked the “use NPC folder structure” box because doing so seemed to fix the issues I was having, even though all my tokens are just in a single folder. Let me know if you still think a pic would be helpful.

 

Thank you,

*	Jeff
