### ISSUE TITLE
Rename `debug` global variable to avoid collisions

### ISSUE THREAD

**Issue by kandashi** [vtt-lair/token-replacer#60]
https://github.com/vtt-lair/token-replacer/blob/a803aa5f2b33d6ad684a4238ba1cf643da1b0583/scripts/token-replacer.js#L16

causes namespace issues when 2 modules use the same variable, this occured with Active Auras and just giving you a heads up

**Comment by vtt-lair** [comment]
Thanks @kandashi, will release a fix to this today
