### ISSUE TITLE
No resize / crop option for layer?

### ISSUE THREAD

**Issue by geoidesic** [vtt-lair/token-replacer#89]
It's the only thing holding this editor back.
One want's to be able to zoom in on a face from an artwork for example.

**Comment by vtt-lair** [comment]
@geoidesic I assume you mean the ability to tokenise soemthing if you don't art work for it? Meaning the following screen:
![image](https://user-images.githubusercontent.com/33215552/152735022-19cfb5fb-3266-491e-b533-06342174b7b9.png)

That's another module that I'm leveraging. Any changes to that will have to be requested on it's github:
https://github.com/mrprimate/vtta-tokenizer
