### ISSUE TITLE
Allow override for a given actor.

### ISSUE THREAD

**Issue by geoidesic** [vtt-lair/token-replacer#91]
Ideally in the elipses menu, allow the option to disable / enable this plugin for a given actor. There are times when the default is a better option, times when it's not, so having both options would make this a much more useful tool. Also this would also solve #90.

**Comment by vtt-lair** [comment]
This functionality already exists. 

Open the actor, got to the Prototype Token on the title bar. 
![image](https://user-images.githubusercontent.com/33215552/152735399-37744933-ce39-4dd6-9d1c-d8781d32753c.png)

Then select appearance
![image](https://user-images.githubusercontent.com/33215552/152735423-d73b3c81-c6c5-4427-bd3b-823264132956.png)

At the bottom there's a place where you can disable Token Replacer for that token
![image](https://user-images.githubusercontent.com/33215552/152735450-7bc46424-03a7-4d82-a8d5-fdd6ac545a79.png)
