### ISSUE TITLE
Doesn't seem to work for CR 1/4 

### ISSUE THREAD

**Issue by geoidesic** [vtt-lair/token-replacer#92]
I managed to get it working fine for CR1 creatures but not for CR1/4, which I assume is the `cr0_25` folder (I tried all of the CR0 folders, nothing works)

**Comment by vtt-lair** [comment]
It depends what your Formatting settings are on the module itself. This is what I'm using:
![image](https://user-images.githubusercontent.com/33215552/152735745-91befc95-fe18-45ce-928e-bc356f6f44d5.png)

And that works fine with: 
![image](https://user-images.githubusercontent.com/33215552/152735809-6cb95540-7989-44a5-8a92-9c882a554136.png)

Example:
![image](https://user-images.githubusercontent.com/33215552/152735869-b3d28371-978d-49e4-9574-d0242645a349.png)
![image](https://user-images.githubusercontent.com/33215552/152735899-51b3cdcc-b38f-49d8-95e0-ca2a7cddc98b.png)
