### ISSUE TITLE
One click for actor and token doesn’t work

### ISSUE THREAD

**Issue by friction1** [vtt-lair/token-replacer#93]
When I don’t have the box checked for separate dialogues for actor and token, when I select a token from the single prompt, it only affects the actor not the default token. I think it should change both right?

**Comment by vtt-lair** [comment]
@friction1 sorry, could you give a few more details or screenshots explaining what you mean? I'm not 100% sure what the issue is here.

**Comment by friction1** [comment]
When the box is unchecked here for separate dialogues, shouldn't it make the token and actor have the same image, the one I select?
https://user-images.githubusercontent.com/11384891/159170085-975e4617-39d3-4ce6-a641-10656cd65863.mov

**Comment by vtt-lair** [comment]
That's Token Variant Art which is a different module created by Aedif (not same module as this one).  That module's github is:

https://github.com/Aedif/TokenVariants
